package com.aijoe.ruleengine.model.map;

import java.util.HashMap;

import static com.aijoe.intouch.model.enumaration.CategoryNameEnum.*;
import static com.aijoe.ruleengine.model.constant.IntentResponseConstants.*;

public class IntentCombinationRespondMap {
    public static final HashMap RESPOND_COMBINATION_MAP = new HashMap<String, String>() {{
        put(KART_UCRETI_IPTALI, KART_UCRETI_IPTALI_RESPOND);
        put(ATM_SORUNLARI, ATM_SORUNLARI_RESPOND);
        put(CM_SIKAYETI, CM_SIKAYETI_RESPOND);
        put(KAMPANYA_SORUNLARI, KAMPANYA_SORUNLARI_RESPOND);
        put(SUBE_SIKAYETI, SUBE_SIKAYETI_RESPOND);
        put(KOMISYON_UCRETLERI_SIKAYETI, KOMISYON_UCRETLERI_SIKAYETLERI_RESPOND);
        put(DIJITAL_KANAL_SIKAYETLERI, DIJITAL_KANAL_SIKAYETLERI_RESPOND);
        put(KART_SORUNLARI, KART_SORUNLARI_RESPOND);
        put(HUKUKI_ISLEMLER, HUKUKI_ISLEMLER_RESPOND);
        put(BORC_YAPILANDIRMA_SORUNLARI, BORC_YAPILANDIRMA_SORUNLARI_RESPOND);
        put(ISLEM_ITIRAZI, ISLEM_ITIRAZI_RESPOND);
        put(KART_TESLIMAT_SORUNLARI, KART_TESLIMAT_SORUNLARI_RESPOND);
        put(HGS_OGS_SORUNLARI, HGS_OGS_SORUNLARI_RESPOND);
        put(ISLEM_IADESI, ISLEM_IADESI_RESPOND);
        put(URUN_BASVURU_REDDI, URUN_BASVURU_REDDI_RESPOND);
        put(URUN_IPTAL_SORUNLARI, URUN_IPTAL_SORUNLARI_RESPOND);
        put(ILETISIM_TERCIHI_DEGISIKLIGI, ILETISIM_TERCIHI_DEGISIKLIGI_RESPOND);
        put(PARA_TRANSFERI_SORUNLARI, PARA_TRANSFERI_SORUNLARI_RESPOND);

        put(KART_UCRETI_IPTALI + "-" + CM_SIKAYETI, KART_UCRETI_IPTALI_CM_SIKAYETI_RESPOND);
        put(KART_UCRETI_IPTALI + "-" + SUBE_SIKAYETI, KART_UCRETI_IPTALI_SUBE_SIKAYETI_RESPOND);
        put(KAMPANYA_SORUNLARI + "-" + CM_SIKAYETI, KAMPANYA_SORUNLARI_CM_SIKAYETI_RESPOND);
        put(KAMPANYA_SORUNLARI + "-" + SUBE_SIKAYETI, KAMPANYA_SORUNLARI_SUBE_SIKAYETI_RESPOND);
        put(ATM_SORUNLARI + "-" + SUBE_SIKAYETI, ATM_SORUNLARI_SUBE_SIKAYETI_RESPOND);

        put(NO_MATCH, NO_MATCH_RESPOND);
    }};
}
